# Building and deploying a custom site using GitHub Actions and GitHub Pages
# https://til.simonwillison.net/github-actions/github-pages
name: Publish site

on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the site
        run: |
          mkdir -p _site
          echo '<h1>Hello, world!</h1>' > _site/index.html
          echo '<a href="https://github.com/ayuen100/pages">Repository</a>' >> _site/index.html
          echo '<a href="https://github.com/ayuen100/pages/actions/workflows/publish.yml">Workflows</a>' >> _site/index.html
          ls -lah
          ls -lah _site
          cd _site
          find . -type f | while read filename; do echo "<a href=\"$filename\">$filename</a>" >> index.html; done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
